////////////////////// e2sm-met-ies.proto //////////////////////
// Protobuf generated from /e2sm_met.asn1 by asn1c-0.9.29
// E2SM-MET-IEs { iso(1) identified-organization(3) dod(6) internet(1) private(4) enterprise(1) oran(53148) e2(1) version2(2) e2sm(2) e2sm-METMON-IEs(97) }

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.19.4
// source: e2sm_met/v1/e2sm_met.proto

package e2sm_met_go

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/onosproject/onos-lib-go/api/asn1/v1/asn1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// range of Integer from e2sm_met.asn1:16
// {CellObjectID}
type CellObjectId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *CellObjectId) Reset() {
	*x = CellObjectId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CellObjectId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellObjectId) ProtoMessage() {}

func (x *CellObjectId) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellObjectId.ProtoReflect.Descriptor instead.
func (*CellObjectId) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{0}
}

func (x *CellObjectId) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// range of Integer from e2sm_met.asn1:20
// {GranularityPeriod}
type GranularityPeriod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: aper:"valueLB:1,valueUB:4294967295"
	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty" aper:"valueLB:1,valueUB:4294967295"`
}

func (x *GranularityPeriod) Reset() {
	*x = GranularityPeriod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GranularityPeriod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GranularityPeriod) ProtoMessage() {}

func (x *GranularityPeriod) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GranularityPeriod.ProtoReflect.Descriptor instead.
func (*GranularityPeriod) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{1}
}

func (x *GranularityPeriod) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// range of Integer from e2sm_met.asn1:20
// {SubscriptionID}
type SubscriptionId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: aper:"valueLB:1,valueUB:4294967295"
	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty" aper:"valueLB:1,valueUB:4294967295"`
}

func (x *SubscriptionId) Reset() {
	*x = SubscriptionId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscriptionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionId) ProtoMessage() {}

func (x *SubscriptionId) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionId.ProtoReflect.Descriptor instead.
func (*SubscriptionId) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{2}
}

func (x *SubscriptionId) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// range of Integer from e2sm_met.asn1:24
// {GlobalMETnode-ID}
type GlobalMetnodeId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: aper:"valueLB:1,valueUB:4294967295"
	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty" aper:"valueLB:1,valueUB:4294967295"`
}

func (x *GlobalMetnodeId) Reset() {
	*x = GlobalMetnodeId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalMetnodeId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalMetnodeId) ProtoMessage() {}

func (x *GlobalMetnodeId) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalMetnodeId.ProtoReflect.Descriptor instead.
func (*GlobalMetnodeId) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{3}
}

func (x *GlobalMetnodeId) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// sequence from e2sm_met.asn1:29
// {RANfunction-Name}
type RanfunctionName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: aper:"sizeExt,sizeLB:1,sizeUB:150"
	RanFunctionShortName string `protobuf:"bytes,1,opt,name=ran_function_short_name,json=ranFunction-ShortName,proto3" json:"ran_function_short_name,omitempty" aper:"sizeExt,sizeLB:1,sizeUB:150"`
	// @inject_tag: aper:"sizeExt,sizeLB:1,sizeUB:1000"
	RanFunctionE2SmOid string `protobuf:"bytes,2,opt,name=ran_function_e2_sm_oid,json=ranFunction-E2SM-OID,proto3" json:"ran_function_e2_sm_oid,omitempty" aper:"sizeExt,sizeLB:1,sizeUB:1000"`
	// @inject_tag: aper:"sizeExt,sizeLB:1,sizeUB:150"
	RanFunctionDescription string `protobuf:"bytes,3,opt,name=ran_function_description,json=ranFunction-Description,proto3" json:"ran_function_description,omitempty" aper:"sizeExt,sizeLB:1,sizeUB:150"`
}

func (x *RanfunctionName) Reset() {
	*x = RanfunctionName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RanfunctionName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RanfunctionName) ProtoMessage() {}

func (x *RanfunctionName) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RanfunctionName.ProtoReflect.Descriptor instead.
func (*RanfunctionName) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{4}
}

func (x *RanfunctionName) GetRanFunctionShortName() string {
	if x != nil {
		return x.RanFunctionShortName
	}
	return ""
}

func (x *RanfunctionName) GetRanFunctionE2SmOid() string {
	if x != nil {
		return x.RanFunctionE2SmOid
	}
	return ""
}

func (x *RanfunctionName) GetRanFunctionDescription() string {
	if x != nil {
		return x.RanFunctionDescription
	}
	return ""
}

// constant Integer from e2sm_met.asn1:39
// {-}
type MaxnoofMeasurementInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: aper:"valueLB:65536,valueUB:65536,"
	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty" aper:"valueLB:65536,valueUB:65536,"`
}

func (x *MaxnoofMeasurementInfo) Reset() {
	*x = MaxnoofMeasurementInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaxnoofMeasurementInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxnoofMeasurementInfo) ProtoMessage() {}

func (x *MaxnoofMeasurementInfo) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxnoofMeasurementInfo.ProtoReflect.Descriptor instead.
func (*MaxnoofMeasurementInfo) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{5}
}

func (x *MaxnoofMeasurementInfo) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// constant Integer from e2sm_met.asn1:40
// {-}
type MaxnoofMeasurementRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: aper:"valueLB:65536,valueUB:65536,"
	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty" aper:"valueLB:65536,valueUB:65536,"`
}

func (x *MaxnoofMeasurementRecord) Reset() {
	*x = MaxnoofMeasurementRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaxnoofMeasurementRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxnoofMeasurementRecord) ProtoMessage() {}

func (x *MaxnoofMeasurementRecord) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxnoofMeasurementRecord.ProtoReflect.Descriptor instead.
func (*MaxnoofMeasurementRecord) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{6}
}

func (x *MaxnoofMeasurementRecord) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// constant Integer from e2sm_met.asn1:41
// {-}
type MaxnoofMeasurementValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: aper:"valueLB:65536,valueUB:65536,"
	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty" aper:"valueLB:65536,valueUB:65536,"`
}

func (x *MaxnoofMeasurementValue) Reset() {
	*x = MaxnoofMeasurementValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaxnoofMeasurementValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxnoofMeasurementValue) ProtoMessage() {}

func (x *MaxnoofMeasurementValue) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxnoofMeasurementValue.ProtoReflect.Descriptor instead.
func (*MaxnoofMeasurementValue) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{7}
}

func (x *MaxnoofMeasurementValue) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// constant Integer from e2sm_met.asn1:45
// {-}
type MaxofUe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: aper:"valueLB:65536,valueUB:65536,"
	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty" aper:"valueLB:65536,valueUB:65536,"`
}

func (x *MaxofUe) Reset() {
	*x = MaxofUe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaxofUe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxofUe) ProtoMessage() {}

func (x *MaxofUe) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxofUe.ProtoReflect.Descriptor instead.
func (*MaxofUe) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{8}
}

func (x *MaxofUe) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// range of Integer from e2sm_met.asn1:47
// {UEID}
type Ueid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: aper:"valueLB:1,valueUB:4294967295"
	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty" aper:"valueLB:1,valueUB:4294967295"`
}

func (x *Ueid) Reset() {
	*x = Ueid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ueid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ueid) ProtoMessage() {}

func (x *Ueid) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ueid.ProtoReflect.Descriptor instead.
func (*Ueid) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{9}
}

func (x *Ueid) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// sequence from e2sm_met.asn1:52
// {UEItem}
type Ueitem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UeId *Ueid `protobuf:"bytes,1,opt,name=ue_id,json=ueID,proto3" json:"ue_id,omitempty"`
	// @inject_tag: aper:"optional"
	UeTag *Uetag `protobuf:"bytes,2,opt,name=ue_tag,json=ueTag,proto3,oneof" json:"ue_tag,omitempty" aper:"optional"`
}

func (x *Ueitem) Reset() {
	*x = Ueitem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ueitem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ueitem) ProtoMessage() {}

func (x *Ueitem) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ueitem.ProtoReflect.Descriptor instead.
func (*Ueitem) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{10}
}

func (x *Ueitem) GetUeId() *Ueid {
	if x != nil {
		return x.UeId
	}
	return nil
}

func (x *Ueitem) GetUeTag() *Uetag {
	if x != nil {
		return x.UeTag
	}
	return nil
}

// sequence from e2sm_met.asn1:61
// {MeasurementInfoList}
type MeasurementInfoList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: aper:"valueExt,sizeLB:1,sizeUB:65535"
	Value []*MeasurementInfoItem `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty" aper:"valueExt,sizeLB:1,sizeUB:65535"`
}

func (x *MeasurementInfoList) Reset() {
	*x = MeasurementInfoList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeasurementInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasurementInfoList) ProtoMessage() {}

func (x *MeasurementInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasurementInfoList.ProtoReflect.Descriptor instead.
func (*MeasurementInfoList) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{11}
}

func (x *MeasurementInfoList) GetValue() []*MeasurementInfoItem {
	if x != nil {
		return x.Value
	}
	return nil
}

// sequence from e2sm_met.asn1:62
// {MeasurementInfoItem}
type MeasurementInfoItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MeasType string `protobuf:"bytes,1,opt,name=meas_type,json=measType,proto3" json:"meas_type,omitempty"`
}

func (x *MeasurementInfoItem) Reset() {
	*x = MeasurementInfoItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeasurementInfoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasurementInfoItem) ProtoMessage() {}

func (x *MeasurementInfoItem) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasurementInfoItem.ProtoReflect.Descriptor instead.
func (*MeasurementInfoItem) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{12}
}

func (x *MeasurementInfoItem) GetMeasType() string {
	if x != nil {
		return x.MeasType
	}
	return ""
}

// sequence from e2sm_met.asn1:68
// {MeasurementData}
type MeasurementData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: aper:"valueExt,sizeLB:1,sizeUB:65535"
	Value []*MeasurementRecord `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty" aper:"valueExt,sizeLB:1,sizeUB:65535"`
}

func (x *MeasurementData) Reset() {
	*x = MeasurementData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeasurementData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasurementData) ProtoMessage() {}

func (x *MeasurementData) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasurementData.ProtoReflect.Descriptor instead.
func (*MeasurementData) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{13}
}

func (x *MeasurementData) GetValue() []*MeasurementRecord {
	if x != nil {
		return x.Value
	}
	return nil
}

// sequence from e2sm_met.asn1:69
// {MeasurementRecord}
type MeasurementRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UeId  *Ueid  `protobuf:"bytes,1,opt,name=ue_id,json=ueID,proto3" json:"ue_id,omitempty"`
	UeTag *Uetag `protobuf:"bytes,2,opt,name=ue_tag,json=ueTag,proto3" json:"ue_tag,omitempty"`
	// @inject_tag: aper:"choiceExt,sizeLB:0,sizeUB:65536"
	MeasRecordItem []*MeasurementRecordItem `protobuf:"bytes,3,rep,name=meas_record_item,json=measRecordItem,proto3" json:"meas_record_item,omitempty" aper:"choiceExt,sizeLB:0,sizeUB:65536"`
}

func (x *MeasurementRecord) Reset() {
	*x = MeasurementRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeasurementRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasurementRecord) ProtoMessage() {}

func (x *MeasurementRecord) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasurementRecord.ProtoReflect.Descriptor instead.
func (*MeasurementRecord) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{14}
}

func (x *MeasurementRecord) GetUeId() *Ueid {
	if x != nil {
		return x.UeId
	}
	return nil
}

func (x *MeasurementRecord) GetUeTag() *Uetag {
	if x != nil {
		return x.UeTag
	}
	return nil
}

func (x *MeasurementRecord) GetMeasRecordItem() []*MeasurementRecordItem {
	if x != nil {
		return x.MeasRecordItem
	}
	return nil
}

// sequence from e2sm_met.asn1:76
// {MeasurementRecordItem}
type MeasurementRecordItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// choice from e2sm_met.asn1:76
	//
	// Types that are assignable to MeasurementRecordItem:
	//	*MeasurementRecordItem_Integer
	//	*MeasurementRecordItem_Real
	//	*MeasurementRecordItem_NoValue
	MeasurementRecordItem isMeasurementRecordItem_MeasurementRecordItem `protobuf_oneof:"measurement_record_item"`
}

func (x *MeasurementRecordItem) Reset() {
	*x = MeasurementRecordItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeasurementRecordItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasurementRecordItem) ProtoMessage() {}

func (x *MeasurementRecordItem) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasurementRecordItem.ProtoReflect.Descriptor instead.
func (*MeasurementRecordItem) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{15}
}

func (m *MeasurementRecordItem) GetMeasurementRecordItem() isMeasurementRecordItem_MeasurementRecordItem {
	if m != nil {
		return m.MeasurementRecordItem
	}
	return nil
}

func (x *MeasurementRecordItem) GetInteger() int64 {
	if x, ok := x.GetMeasurementRecordItem().(*MeasurementRecordItem_Integer); ok {
		return x.Integer
	}
	return 0
}

func (x *MeasurementRecordItem) GetReal() float64 {
	if x, ok := x.GetMeasurementRecordItem().(*MeasurementRecordItem_Real); ok {
		return x.Real
	}
	return 0
}

func (x *MeasurementRecordItem) GetNoValue() int32 {
	if x, ok := x.GetMeasurementRecordItem().(*MeasurementRecordItem_NoValue); ok {
		return x.NoValue
	}
	return 0
}

type isMeasurementRecordItem_MeasurementRecordItem interface {
	isMeasurementRecordItem_MeasurementRecordItem()
}

type MeasurementRecordItem_Integer struct {
	// @inject_tag: aper:"choiceIdx:1,valueLB:0,valueUB:4294967295"
	Integer int64 `protobuf:"varint,1,opt,name=integer,proto3,oneof" aper:"choiceIdx:1,valueLB:0,valueUB:4294967295"`
}

type MeasurementRecordItem_Real struct {
	// @inject_tag: aper:"choiceIdx:2"
	Real float64 `protobuf:"fixed64,2,opt,name=real,proto3,oneof" aper:"choiceIdx:2"`
}

type MeasurementRecordItem_NoValue struct {
	// @inject_tag: aper:"choiceIdx:3,valueLB:0,valueUB:0"
	NoValue int32 `protobuf:"varint,3,opt,name=no_value,json=noValue,proto3,oneof" aper:"choiceIdx:3,valueLB:0,valueUB:0"`
}

func (*MeasurementRecordItem_Integer) isMeasurementRecordItem_MeasurementRecordItem() {}

func (*MeasurementRecordItem_Real) isMeasurementRecordItem_MeasurementRecordItem() {}

func (*MeasurementRecordItem_NoValue) isMeasurementRecordItem_MeasurementRecordItem() {}

// sequence from e2sm_met.asn1:94
// {E2SM-MET-EventTriggerDefinition}
type E2SmMetEventTriggerDefinition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: aper:"choiceExt"
	EventDefinitionFormats *EventTriggerDefinitionFormats `protobuf:"bytes,1,opt,name=event_definition_formats,json=eventDefinition-formats,proto3" json:"event_definition_formats,omitempty" aper:"choiceExt"`
}

func (x *E2SmMetEventTriggerDefinition) Reset() {
	*x = E2SmMetEventTriggerDefinition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *E2SmMetEventTriggerDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2SmMetEventTriggerDefinition) ProtoMessage() {}

func (x *E2SmMetEventTriggerDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2SmMetEventTriggerDefinition.ProtoReflect.Descriptor instead.
func (*E2SmMetEventTriggerDefinition) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{16}
}

func (x *E2SmMetEventTriggerDefinition) GetEventDefinitionFormats() *EventTriggerDefinitionFormats {
	if x != nil {
		return x.EventDefinitionFormats
	}
	return nil
}

type EventTriggerDefinitionFormats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to E2SmMetEventTriggerDefinition:
	//	*EventTriggerDefinitionFormats_EventDefinitionFormat1
	E2SmMetEventTriggerDefinition isEventTriggerDefinitionFormats_E2SmMetEventTriggerDefinition `protobuf_oneof:"e2_sm_met_event_trigger_definition"`
}

func (x *EventTriggerDefinitionFormats) Reset() {
	*x = EventTriggerDefinitionFormats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventTriggerDefinitionFormats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTriggerDefinitionFormats) ProtoMessage() {}

func (x *EventTriggerDefinitionFormats) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTriggerDefinitionFormats.ProtoReflect.Descriptor instead.
func (*EventTriggerDefinitionFormats) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{17}
}

func (m *EventTriggerDefinitionFormats) GetE2SmMetEventTriggerDefinition() isEventTriggerDefinitionFormats_E2SmMetEventTriggerDefinition {
	if m != nil {
		return m.E2SmMetEventTriggerDefinition
	}
	return nil
}

func (x *EventTriggerDefinitionFormats) GetEventDefinitionFormat1() *E2SmMetEventTriggerDefinitionFormat1 {
	if x, ok := x.GetE2SmMetEventTriggerDefinition().(*EventTriggerDefinitionFormats_EventDefinitionFormat1); ok {
		return x.EventDefinitionFormat1
	}
	return nil
}

type isEventTriggerDefinitionFormats_E2SmMetEventTriggerDefinition interface {
	isEventTriggerDefinitionFormats_E2SmMetEventTriggerDefinition()
}

type EventTriggerDefinitionFormats_EventDefinitionFormat1 struct {
	// @inject_tag: aper:"choiceIdx:1,valueExt"
	EventDefinitionFormat1 *E2SmMetEventTriggerDefinitionFormat1 `protobuf:"bytes,1,opt,name=event_definition_format1,json=eventDefinition_Format1,proto3,oneof" aper:"choiceIdx:1,valueExt"`
}

func (*EventTriggerDefinitionFormats_EventDefinitionFormat1) isEventTriggerDefinitionFormats_E2SmMetEventTriggerDefinition() {
}

// sequence from e2sm_met.asn1:99
// {E2SM-MET-EventTriggerDefinition-Format1}
type E2SmMetEventTriggerDefinitionFormat1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: aper:"valueLB:1,valueUB:4294967295"
	ReportingPeriod int64 `protobuf:"varint,1,opt,name=reporting_period,json=reportingPeriod,proto3" json:"reporting_period,omitempty" aper:"valueLB:1,valueUB:4294967295"`
}

func (x *E2SmMetEventTriggerDefinitionFormat1) Reset() {
	*x = E2SmMetEventTriggerDefinitionFormat1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *E2SmMetEventTriggerDefinitionFormat1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2SmMetEventTriggerDefinitionFormat1) ProtoMessage() {}

func (x *E2SmMetEventTriggerDefinitionFormat1) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2SmMetEventTriggerDefinitionFormat1.ProtoReflect.Descriptor instead.
func (*E2SmMetEventTriggerDefinitionFormat1) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{18}
}

func (x *E2SmMetEventTriggerDefinitionFormat1) GetReportingPeriod() int64 {
	if x != nil {
		return x.ReportingPeriod
	}
	return 0
}

// sequence from e2sm_met.asn1:115
// {E2SM-MET-IndicationHeader}
type E2SmMetIndicationHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: aper:"choiceExt"
	IndicationHeaderFormats *IndicationHeaderFormats `protobuf:"bytes,1,opt,name=indication_header_formats,json=indicationHeader-formats,proto3" json:"indication_header_formats,omitempty" aper:"choiceExt"`
}

func (x *E2SmMetIndicationHeader) Reset() {
	*x = E2SmMetIndicationHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *E2SmMetIndicationHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2SmMetIndicationHeader) ProtoMessage() {}

func (x *E2SmMetIndicationHeader) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2SmMetIndicationHeader.ProtoReflect.Descriptor instead.
func (*E2SmMetIndicationHeader) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{19}
}

func (x *E2SmMetIndicationHeader) GetIndicationHeaderFormats() *IndicationHeaderFormats {
	if x != nil {
		return x.IndicationHeaderFormats
	}
	return nil
}

type IndicationHeaderFormats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to E2SmMetIndicationHeader:
	//	*IndicationHeaderFormats_IndicationHeaderFormat1
	E2SmMetIndicationHeader isIndicationHeaderFormats_E2SmMetIndicationHeader `protobuf_oneof:"e2_sm_met_indication_header"`
}

func (x *IndicationHeaderFormats) Reset() {
	*x = IndicationHeaderFormats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndicationHeaderFormats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndicationHeaderFormats) ProtoMessage() {}

func (x *IndicationHeaderFormats) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndicationHeaderFormats.ProtoReflect.Descriptor instead.
func (*IndicationHeaderFormats) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{20}
}

func (m *IndicationHeaderFormats) GetE2SmMetIndicationHeader() isIndicationHeaderFormats_E2SmMetIndicationHeader {
	if m != nil {
		return m.E2SmMetIndicationHeader
	}
	return nil
}

func (x *IndicationHeaderFormats) GetIndicationHeaderFormat1() *E2SmMetIndicationHeaderFormat1 {
	if x, ok := x.GetE2SmMetIndicationHeader().(*IndicationHeaderFormats_IndicationHeaderFormat1); ok {
		return x.IndicationHeaderFormat1
	}
	return nil
}

type isIndicationHeaderFormats_E2SmMetIndicationHeader interface {
	isIndicationHeaderFormats_E2SmMetIndicationHeader()
}

type IndicationHeaderFormats_IndicationHeaderFormat1 struct {
	// @inject_tag: aper:"valueExt,choiceIdx:1"
	IndicationHeaderFormat1 *E2SmMetIndicationHeaderFormat1 `protobuf:"bytes,1,opt,name=indication_header_format1,json=indicationHeader_Format1,proto3,oneof" aper:"valueExt,choiceIdx:1"`
}

func (*IndicationHeaderFormats_IndicationHeaderFormat1) isIndicationHeaderFormats_E2SmMetIndicationHeader() {
}

// sequence from e2sm_met.asn1:120
// {E2SM-MET-IndicationHeader-Format1}
type E2SmMetIndicationHeaderFormat1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ColletStartTime *TimeStamp `protobuf:"bytes,1,opt,name=collet_start_time,json=colletStartTime,proto3" json:"collet_start_time,omitempty"`
	// @inject_tag: aper:"optional,sizeExt,sizeLB:0,sizeUB:15"
	FileFormatversion *string `protobuf:"bytes,2,opt,name=file_formatversion,json=fileFormatversion,proto3,oneof" json:"file_formatversion,omitempty" aper:"optional,sizeExt,sizeLB:0,sizeUB:15"`
	// @inject_tag: aper:"optional,sizeExt,sizeLB:0,sizeUB:400"
	SenderName *string `protobuf:"bytes,3,opt,name=sender_name,json=senderName,proto3,oneof" json:"sender_name,omitempty" aper:"optional,sizeExt,sizeLB:0,sizeUB:400"`
	// @inject_tag: aper:"optional"
	MetNodeId *GlobalMetnodeId `protobuf:"bytes,4,opt,name=met_node_id,json=metNodeID,proto3,oneof" json:"met_node_id,omitempty" aper:"optional"`
}

func (x *E2SmMetIndicationHeaderFormat1) Reset() {
	*x = E2SmMetIndicationHeaderFormat1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *E2SmMetIndicationHeaderFormat1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2SmMetIndicationHeaderFormat1) ProtoMessage() {}

func (x *E2SmMetIndicationHeaderFormat1) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2SmMetIndicationHeaderFormat1.ProtoReflect.Descriptor instead.
func (*E2SmMetIndicationHeaderFormat1) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{21}
}

func (x *E2SmMetIndicationHeaderFormat1) GetColletStartTime() *TimeStamp {
	if x != nil {
		return x.ColletStartTime
	}
	return nil
}

func (x *E2SmMetIndicationHeaderFormat1) GetFileFormatversion() string {
	if x != nil && x.FileFormatversion != nil {
		return *x.FileFormatversion
	}
	return ""
}

func (x *E2SmMetIndicationHeaderFormat1) GetSenderName() string {
	if x != nil && x.SenderName != nil {
		return *x.SenderName
	}
	return ""
}

func (x *E2SmMetIndicationHeaderFormat1) GetMetNodeId() *GlobalMetnodeId {
	if x != nil {
		return x.MetNodeId
	}
	return nil
}

// sequence from e2sm_met.asn1:135
// {E2SM-MET-IndicationMessage}
type E2SmMetIndicationMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: aper:"choiceExt"
	IndicationMessageFormats *IndicationMessageFormats `protobuf:"bytes,1,opt,name=indication_message_formats,json=indicationMessage-formats,proto3" json:"indication_message_formats,omitempty" aper:"choiceExt"`
}

func (x *E2SmMetIndicationMessage) Reset() {
	*x = E2SmMetIndicationMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *E2SmMetIndicationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2SmMetIndicationMessage) ProtoMessage() {}

func (x *E2SmMetIndicationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2SmMetIndicationMessage.ProtoReflect.Descriptor instead.
func (*E2SmMetIndicationMessage) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{22}
}

func (x *E2SmMetIndicationMessage) GetIndicationMessageFormats() *IndicationMessageFormats {
	if x != nil {
		return x.IndicationMessageFormats
	}
	return nil
}

type IndicationMessageFormats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to E2SmMetIndicationMessage:
	//	*IndicationMessageFormats_IndicationMessageFormat1
	E2SmMetIndicationMessage isIndicationMessageFormats_E2SmMetIndicationMessage `protobuf_oneof:"e2_sm_met_indication_message"`
}

func (x *IndicationMessageFormats) Reset() {
	*x = IndicationMessageFormats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndicationMessageFormats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndicationMessageFormats) ProtoMessage() {}

func (x *IndicationMessageFormats) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndicationMessageFormats.ProtoReflect.Descriptor instead.
func (*IndicationMessageFormats) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{23}
}

func (m *IndicationMessageFormats) GetE2SmMetIndicationMessage() isIndicationMessageFormats_E2SmMetIndicationMessage {
	if m != nil {
		return m.E2SmMetIndicationMessage
	}
	return nil
}

func (x *IndicationMessageFormats) GetIndicationMessageFormat1() *E2SmMetIndicationMessageFormat1 {
	if x, ok := x.GetE2SmMetIndicationMessage().(*IndicationMessageFormats_IndicationMessageFormat1); ok {
		return x.IndicationMessageFormat1
	}
	return nil
}

type isIndicationMessageFormats_E2SmMetIndicationMessage interface {
	isIndicationMessageFormats_E2SmMetIndicationMessage()
}

type IndicationMessageFormats_IndicationMessageFormat1 struct {
	// @inject_tag: aper:"valueExt,choiceIdx:1"
	IndicationMessageFormat1 *E2SmMetIndicationMessageFormat1 `protobuf:"bytes,1,opt,name=indication_message_format1,json=indicationMessage_Format1,proto3,oneof" aper:"valueExt,choiceIdx:1"`
}

func (*IndicationMessageFormats_IndicationMessageFormat1) isIndicationMessageFormats_E2SmMetIndicationMessage() {
}

// sequence from e2sm_met.asn1:140
// {E2SM-MET-IndicationMessage-Format1}
type E2SmMetIndicationMessageFormat1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubscriptId *SubscriptionId `protobuf:"bytes,1,opt,name=subscript_id,json=subscriptID,proto3" json:"subscript_id,omitempty"`
	// @inject_tag: aper:"optional"
	CellObjId *CellObjectId `protobuf:"bytes,2,opt,name=cell_obj_id,json=cellObjID,proto3,oneof" json:"cell_obj_id,omitempty" aper:"optional"`
	// @inject_tag: aper:"optional"
	GranulPeriod *GranularityPeriod `protobuf:"bytes,3,opt,name=granul_period,json=granulPeriod,proto3,oneof" json:"granul_period,omitempty" aper:"optional"`
	// @inject_tag: aper:"optional"
	MeasInfoList *MeasurementInfoList `protobuf:"bytes,4,opt,name=meas_info_list,json=measInfoList,proto3,oneof" json:"meas_info_list,omitempty" aper:"optional"`
	MeasData     *MeasurementData     `protobuf:"bytes,5,opt,name=meas_data,json=measData,proto3" json:"meas_data,omitempty"`
}

func (x *E2SmMetIndicationMessageFormat1) Reset() {
	*x = E2SmMetIndicationMessageFormat1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *E2SmMetIndicationMessageFormat1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2SmMetIndicationMessageFormat1) ProtoMessage() {}

func (x *E2SmMetIndicationMessageFormat1) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2SmMetIndicationMessageFormat1.ProtoReflect.Descriptor instead.
func (*E2SmMetIndicationMessageFormat1) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{24}
}

func (x *E2SmMetIndicationMessageFormat1) GetSubscriptId() *SubscriptionId {
	if x != nil {
		return x.SubscriptId
	}
	return nil
}

func (x *E2SmMetIndicationMessageFormat1) GetCellObjId() *CellObjectId {
	if x != nil {
		return x.CellObjId
	}
	return nil
}

func (x *E2SmMetIndicationMessageFormat1) GetGranulPeriod() *GranularityPeriod {
	if x != nil {
		return x.GranulPeriod
	}
	return nil
}

func (x *E2SmMetIndicationMessageFormat1) GetMeasInfoList() *MeasurementInfoList {
	if x != nil {
		return x.MeasInfoList
	}
	return nil
}

func (x *E2SmMetIndicationMessageFormat1) GetMeasData() *MeasurementData {
	if x != nil {
		return x.MeasData
	}
	return nil
}

// sequence from e2sm_met.asn1:153
// {E2SM-MET-RANfunction-Description}
type E2SmMetRanfunctionDescription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RanFunctionName *RanfunctionName `protobuf:"bytes,1,opt,name=ran_function_name,json=ranFunction-Name,proto3" json:"ran_function_name,omitempty"`
}

func (x *E2SmMetRanfunctionDescription) Reset() {
	*x = E2SmMetRanfunctionDescription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *E2SmMetRanfunctionDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2SmMetRanfunctionDescription) ProtoMessage() {}

func (x *E2SmMetRanfunctionDescription) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2SmMetRanfunctionDescription.ProtoReflect.Descriptor instead.
func (*E2SmMetRanfunctionDescription) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{25}
}

func (x *E2SmMetRanfunctionDescription) GetRanFunctionName() *RanfunctionName {
	if x != nil {
		return x.RanFunctionName
	}
	return nil
}

//{TimeStamp}
type TimeStamp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: aper:"sizeLB:4,sizeUB:4"
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty" aper:"sizeLB:4,sizeUB:4"`
}

func (x *TimeStamp) Reset() {
	*x = TimeStamp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeStamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeStamp) ProtoMessage() {}

func (x *TimeStamp) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeStamp.ProtoReflect.Descriptor instead.
func (*TimeStamp) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{26}
}

func (x *TimeStamp) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

//{CellObjectID}
type Uetag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: aper:"sizeExt,sizeLB:0,sizeUB:400"
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty" aper:"sizeExt,sizeLB:0,sizeUB:400"`
}

func (x *Uetag) Reset() {
	*x = Uetag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Uetag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uetag) ProtoMessage() {}

func (x *Uetag) ProtoReflect() protoreflect.Message {
	mi := &file_e2sm_met_v1_e2sm_met_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uetag.ProtoReflect.Descriptor instead.
func (*Uetag) Descriptor() ([]byte, []int) {
	return file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP(), []int{27}
}

func (x *Uetag) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_e2sm_met_v1_e2sm_met_proto protoreflect.FileDescriptor

var file_e2sm_met_v1_e2sm_met_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x65, 0x32, 0x73, 0x6d, 0x5f, 0x6d, 0x65, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x32,
	0x73, 0x6d, 0x5f, 0x6d, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x65, 0x32,
	0x73, 0x6d, 0x5f, 0x6d, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x1a, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x61, 0x73, 0x6e, 0x31, 0x2f, 0x76, 0x31, 0x2f, 0x61,
	0x73, 0x6e, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x0c, 0x43, 0x65, 0x6c,
	0x6c, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0a, 0xfa, 0x42, 0x07, 0x1a, 0x05, 0x18,
	0xff, 0x01, 0x28, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x38, 0x0a, 0x11, 0x47,
	0x72, 0x61, 0x6e, 0x75, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64,
	0x12, 0x23, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42,
	0x0d, 0xfa, 0x42, 0x0a, 0x22, 0x08, 0x18, 0xff, 0xff, 0xff, 0xff, 0x0f, 0x28, 0x01, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x35, 0x0a, 0x0e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x0d, 0xfa, 0x42, 0x0a, 0x22, 0x08, 0x18, 0xff, 0xff,
	0xff, 0xff, 0x0f, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x36, 0x0a, 0x0f,
	0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x4d, 0x65, 0x74, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12,
	0x23, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x0d,
	0xfa, 0x42, 0x0a, 0x22, 0x08, 0x18, 0xff, 0xff, 0xff, 0xff, 0x0f, 0x28, 0x01, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0xde, 0x01, 0x0a, 0x0f, 0x52, 0x61, 0x6e, 0x66, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x42, 0x0a, 0x17, 0x72, 0x61, 0x6e, 0x5f,
	0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0xfa, 0x42, 0x07, 0x72, 0x05,
	0x10, 0x01, 0x18, 0x96, 0x01, 0x52, 0x15, 0x72, 0x61, 0x6e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2d, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x40, 0x0a, 0x16,
	0x72, 0x61, 0x6e, 0x5f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x65, 0x32, 0x5f,
	0x73, 0x6d, 0x5f, 0x6f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0xfa, 0x42,
	0x07, 0x72, 0x05, 0x10, 0x01, 0x18, 0xe8, 0x07, 0x52, 0x14, 0x72, 0x61, 0x6e, 0x46, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x45, 0x32, 0x53, 0x4d, 0x2d, 0x4f, 0x49, 0x44, 0x12, 0x45,
	0x0a, 0x18, 0x72, 0x61, 0x6e, 0x5f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x0a, 0xfa, 0x42, 0x07, 0x72, 0x05, 0x10, 0x01, 0x18, 0x96, 0x01, 0x52, 0x17, 0x72, 0x61,
	0x6e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x39, 0x0a, 0x16, 0x4d, 0x61, 0x78, 0x6e, 0x6f, 0x6f, 0x66,
	0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x1f, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x09,
	0xfa, 0x42, 0x06, 0x1a, 0x04, 0x08, 0x80, 0x80, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x3b, 0x0a, 0x18, 0x4d, 0x61, 0x78, 0x6e, 0x6f, 0x6f, 0x66, 0x4d, 0x65, 0x61, 0x73, 0x75,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1f, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x09, 0xfa, 0x42, 0x06,
	0x1a, 0x04, 0x08, 0x80, 0x80, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3a, 0x0a,
	0x17, 0x4d, 0x61, 0x78, 0x6e, 0x6f, 0x6f, 0x66, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x1a, 0x04, 0x08, 0x80,
	0x80, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2a, 0x0a, 0x07, 0x4d, 0x61, 0x78,
	0x6f, 0x66, 0x55, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x1a, 0x04, 0x08, 0x80, 0x80, 0x04, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2b, 0x0a, 0x04, 0x55, 0x65, 0x69, 0x64, 0x12, 0x23, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x0d, 0xfa, 0x42,
	0x0a, 0x22, 0x08, 0x18, 0xff, 0xff, 0xff, 0xff, 0x0f, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x6b, 0x0a, 0x06, 0x55, 0x65, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x26, 0x0a, 0x05,
	0x75, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x65, 0x32,
	0x73, 0x6d, 0x5f, 0x6d, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x65, 0x69, 0x64, 0x52, 0x04,
	0x75, 0x65, 0x49, 0x44, 0x12, 0x2e, 0x0a, 0x06, 0x75, 0x65, 0x5f, 0x74, 0x61, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x65, 0x32, 0x73, 0x6d, 0x5f, 0x6d, 0x65, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x55, 0x65, 0x74, 0x61, 0x67, 0x48, 0x00, 0x52, 0x05, 0x75, 0x65, 0x54, 0x61,
	0x67, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x75, 0x65, 0x5f, 0x74, 0x61, 0x67, 0x22,
	0x4d, 0x0a, 0x13, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x65, 0x32, 0x73, 0x6d, 0x5f, 0x6d, 0x65, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3d,
	0x0a, 0x13, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x26, 0x0a, 0x09, 0x6d, 0x65, 0x61, 0x73, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x72, 0x04, 0x10,
	0x00, 0x18, 0x0f, 0x52, 0x08, 0x6d, 0x65, 0x61, 0x73, 0x54, 0x79, 0x70, 0x65, 0x22, 0x47, 0x0a,
	0x0f, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x34, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x65, 0x32, 0x73, 0x6d, 0x5f, 0x6d, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65,
	0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xc2, 0x01, 0x0a, 0x11, 0x4d, 0x65, 0x61, 0x73, 0x75,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x26, 0x0a, 0x05,
	0x75, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x65, 0x32,
	0x73, 0x6d, 0x5f, 0x6d, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x65, 0x69, 0x64, 0x52, 0x04,
	0x75, 0x65, 0x49, 0x44, 0x12, 0x29, 0x0a, 0x06, 0x75, 0x65, 0x5f, 0x74, 0x61, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x65, 0x32, 0x73, 0x6d, 0x5f, 0x6d, 0x65, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x55, 0x65, 0x74, 0x61, 0x67, 0x52, 0x05, 0x75, 0x65, 0x54, 0x61, 0x67, 0x12,
	0x5a, 0x0a, 0x10, 0x6d, 0x65, 0x61, 0x73, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x69,
	0x74, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x65, 0x32, 0x73, 0x6d,
	0x5f, 0x6d, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x42, 0x0c, 0xfa,
	0x42, 0x09, 0x92, 0x01, 0x06, 0x08, 0x00, 0x10, 0x80, 0x80, 0x04, 0x52, 0x0e, 0x6d, 0x65, 0x61,
	0x73, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x81, 0x01, 0x0a, 0x15,
	0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1a, 0x0a, 0x07, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x07, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x65,
	0x72, 0x12, 0x14, 0x0a, 0x04, 0x72, 0x65, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x48,
	0x00, 0x52, 0x04, 0x72, 0x65, 0x61, 0x6c, 0x12, 0x1b, 0x0a, 0x08, 0x6e, 0x6f, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x07, 0x6e, 0x6f, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x42, 0x19, 0x0a, 0x17, 0x6d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x22,
	0x86, 0x01, 0x0a, 0x1d, 0x45, 0x32, 0x53, 0x6d, 0x4d, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x65, 0x0a, 0x18, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x65, 0x32, 0x73, 0x6d, 0x5f, 0x6d, 0x65, 0x74, 0x2e, 0x76,
	0x31, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x44, 0x65,
	0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x52,
	0x17, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x2d, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x22, 0xb5, 0x01, 0x0a, 0x1d, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x12, 0x6e, 0x0a, 0x18, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x65,
	0x32, 0x73, 0x6d, 0x5f, 0x6d, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x32, 0x53, 0x6d, 0x4d,
	0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x44, 0x65,
	0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x31, 0x48,
	0x00, 0x52, 0x17, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x31, 0x42, 0x24, 0x0a, 0x22, 0x65, 0x32,
	0x5f, 0x73, 0x6d, 0x5f, 0x6d, 0x65, 0x74, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x72,
	0x69, 0x67, 0x67, 0x65, 0x72, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x51, 0x0a, 0x24, 0x45, 0x32, 0x53, 0x6d, 0x4d, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x31, 0x12, 0x29, 0x0a, 0x10, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x50, 0x65, 0x72,
	0x69, 0x6f, 0x64, 0x22, 0x7c, 0x0a, 0x17, 0x45, 0x32, 0x53, 0x6d, 0x4d, 0x65, 0x74, 0x49, 0x6e,
	0x64, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x61,
	0x0a, 0x19, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x24, 0x2e, 0x65, 0x32, 0x73, 0x6d, 0x5f, 0x6d, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x52, 0x18, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2d, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x73, 0x22, 0xa4, 0x01, 0x0a, 0x17, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x12, 0x6a, 0x0a,
	0x19, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2b, 0x2e, 0x65, 0x32, 0x73, 0x6d, 0x5f, 0x6d, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x45,
	0x32, 0x53, 0x6d, 0x4d, 0x65, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x31, 0x48, 0x00, 0x52,
	0x18, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x5f, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x31, 0x42, 0x1d, 0x0a, 0x1b, 0x65, 0x32, 0x5f,
	0x73, 0x6d, 0x5f, 0x6d, 0x65, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0xcf, 0x02, 0x0a, 0x1e, 0x45, 0x32, 0x53,
	0x6d, 0x4d, 0x65, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x31, 0x12, 0x42, 0x0a, 0x11, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x65, 0x32, 0x73, 0x6d, 0x5f, 0x6d, 0x65,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0f,
	0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x3d, 0x0a, 0x12, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x09, 0xfa, 0x42, 0x06,
	0x72, 0x04, 0x10, 0x00, 0x18, 0x0f, 0x48, 0x00, 0x52, 0x11, 0x66, 0x69, 0x6c, 0x65, 0x46, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x30,
	0x0a, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x0a, 0xfa, 0x42, 0x07, 0x72, 0x05, 0x10, 0x00, 0x18, 0x90, 0x03, 0x48,
	0x01, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01,
	0x12, 0x41, 0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x65, 0x32, 0x73, 0x6d, 0x5f, 0x6d, 0x65, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x4d, 0x65, 0x74, 0x6e, 0x6f, 0x64,
	0x65, 0x49, 0x64, 0x48, 0x02, 0x52, 0x09, 0x6d, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44,
	0x88, 0x01, 0x01, 0x42, 0x15, 0x0a, 0x13, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x6d,
	0x65, 0x74, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x22, 0x80, 0x01, 0x0a, 0x18, 0x45,
	0x32, 0x53, 0x6d, 0x4d, 0x65, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x64, 0x0a, 0x1a, 0x69, 0x6e, 0x64, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x65, 0x32,
	0x73, 0x6d, 0x5f, 0x6d, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x73, 0x52, 0x19, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2d, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x22, 0xa9, 0x01,
	0x0a, 0x18, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x12, 0x6d, 0x0a, 0x1a, 0x69, 0x6e,
	0x64, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c,
	0x2e, 0x65, 0x32, 0x73, 0x6d, 0x5f, 0x6d, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x32, 0x53,
	0x6d, 0x4d, 0x65, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x31, 0x48, 0x00, 0x52, 0x19,
	0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x31, 0x42, 0x1e, 0x0a, 0x1c, 0x65, 0x32, 0x5f,
	0x73, 0x6d, 0x5f, 0x6d, 0x65, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xa8, 0x03, 0x0a, 0x1f, 0x45, 0x32,
	0x53, 0x6d, 0x4d, 0x65, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x31, 0x12, 0x3e, 0x0a,
	0x0c, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x65, 0x32, 0x73, 0x6d, 0x5f, 0x6d, 0x65, 0x74, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x52, 0x0b, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x49, 0x44, 0x12, 0x3e, 0x0a,
	0x0b, 0x63, 0x65, 0x6c, 0x6c, 0x5f, 0x6f, 0x62, 0x6a, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x65, 0x32, 0x73, 0x6d, 0x5f, 0x6d, 0x65, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x65, 0x6c, 0x6c, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x48, 0x00, 0x52,
	0x09, 0x63, 0x65, 0x6c, 0x6c, 0x4f, 0x62, 0x6a, 0x49, 0x44, 0x88, 0x01, 0x01, 0x12, 0x48, 0x0a,
	0x0d, 0x67, 0x72, 0x61, 0x6e, 0x75, 0x6c, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x65, 0x32, 0x73, 0x6d, 0x5f, 0x6d, 0x65, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x72, 0x61, 0x6e, 0x75, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x50, 0x65,
	0x72, 0x69, 0x6f, 0x64, 0x48, 0x01, 0x52, 0x0c, 0x67, 0x72, 0x61, 0x6e, 0x75, 0x6c, 0x50, 0x65,
	0x72, 0x69, 0x6f, 0x64, 0x88, 0x01, 0x01, 0x12, 0x4b, 0x0a, 0x0e, 0x6d, 0x65, 0x61, 0x73, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x65, 0x32, 0x73, 0x6d, 0x5f, 0x6d, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65,
	0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73,
	0x74, 0x48, 0x02, 0x52, 0x0c, 0x6d, 0x65, 0x61, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73,
	0x74, 0x88, 0x01, 0x01, 0x12, 0x39, 0x0a, 0x09, 0x6d, 0x65, 0x61, 0x73, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x65, 0x32, 0x73, 0x6d, 0x5f, 0x6d,
	0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x61, 0x73, 0x44, 0x61, 0x74, 0x61, 0x42,
	0x0e, 0x0a, 0x0c, 0x5f, 0x63, 0x65, 0x6c, 0x6c, 0x5f, 0x6f, 0x62, 0x6a, 0x5f, 0x69, 0x64, 0x42,
	0x10, 0x0a, 0x0e, 0x5f, 0x67, 0x72, 0x61, 0x6e, 0x75, 0x6c, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f,
	0x64, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x6d, 0x65, 0x61, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x22, 0x6a, 0x0a, 0x1d, 0x45, 0x32, 0x53, 0x6d, 0x4d, 0x65, 0x74, 0x52,
	0x61, 0x6e, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x49, 0x0a, 0x11, 0x72, 0x61, 0x6e, 0x5f, 0x66, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x65, 0x32, 0x73, 0x6d, 0x5f, 0x6d, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x61, 0x6e, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x10,
	0x72, 0x61, 0x6e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x2a, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1d, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x42, 0x07, 0xfa, 0x42,
	0x04, 0x7a, 0x02, 0x68, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x29, 0x0a, 0x05,
	0x55, 0x65, 0x74, 0x61, 0x67, 0x12, 0x20, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0xfa, 0x42, 0x07, 0x72, 0x05, 0x10, 0x00, 0x18, 0x96, 0x01,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x48, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x62, 0x64, 0x6f, 0x75, 0x54, 0x6c, 0x69, 0x6c, 0x69,
	0x2f, 0x6f, 0x6e, 0x6f, 0x73, 0x2d, 0x65, 0x32, 0x2d, 0x73, 0x6d, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x65, 0x32, 0x73, 0x6d, 0x5f, 0x6d,
	0x65, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x32, 0x73, 0x6d, 0x2d, 0x6d, 0x65, 0x74, 0x2d, 0x67,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_e2sm_met_v1_e2sm_met_proto_rawDescOnce sync.Once
	file_e2sm_met_v1_e2sm_met_proto_rawDescData = file_e2sm_met_v1_e2sm_met_proto_rawDesc
)

func file_e2sm_met_v1_e2sm_met_proto_rawDescGZIP() []byte {
	file_e2sm_met_v1_e2sm_met_proto_rawDescOnce.Do(func() {
		file_e2sm_met_v1_e2sm_met_proto_rawDescData = protoimpl.X.CompressGZIP(file_e2sm_met_v1_e2sm_met_proto_rawDescData)
	})
	return file_e2sm_met_v1_e2sm_met_proto_rawDescData
}

var file_e2sm_met_v1_e2sm_met_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_e2sm_met_v1_e2sm_met_proto_goTypes = []interface{}{
	(*CellObjectId)(nil),                         // 0: e2sm_met.v1.CellObjectId
	(*GranularityPeriod)(nil),                    // 1: e2sm_met.v1.GranularityPeriod
	(*SubscriptionId)(nil),                       // 2: e2sm_met.v1.SubscriptionId
	(*GlobalMetnodeId)(nil),                      // 3: e2sm_met.v1.GlobalMetnodeId
	(*RanfunctionName)(nil),                      // 4: e2sm_met.v1.RanfunctionName
	(*MaxnoofMeasurementInfo)(nil),               // 5: e2sm_met.v1.MaxnoofMeasurementInfo
	(*MaxnoofMeasurementRecord)(nil),             // 6: e2sm_met.v1.MaxnoofMeasurementRecord
	(*MaxnoofMeasurementValue)(nil),              // 7: e2sm_met.v1.MaxnoofMeasurementValue
	(*MaxofUe)(nil),                              // 8: e2sm_met.v1.MaxofUe
	(*Ueid)(nil),                                 // 9: e2sm_met.v1.Ueid
	(*Ueitem)(nil),                               // 10: e2sm_met.v1.Ueitem
	(*MeasurementInfoList)(nil),                  // 11: e2sm_met.v1.MeasurementInfoList
	(*MeasurementInfoItem)(nil),                  // 12: e2sm_met.v1.MeasurementInfoItem
	(*MeasurementData)(nil),                      // 13: e2sm_met.v1.MeasurementData
	(*MeasurementRecord)(nil),                    // 14: e2sm_met.v1.MeasurementRecord
	(*MeasurementRecordItem)(nil),                // 15: e2sm_met.v1.MeasurementRecordItem
	(*E2SmMetEventTriggerDefinition)(nil),        // 16: e2sm_met.v1.E2SmMetEventTriggerDefinition
	(*EventTriggerDefinitionFormats)(nil),        // 17: e2sm_met.v1.EventTriggerDefinitionFormats
	(*E2SmMetEventTriggerDefinitionFormat1)(nil), // 18: e2sm_met.v1.E2SmMetEventTriggerDefinitionFormat1
	(*E2SmMetIndicationHeader)(nil),              // 19: e2sm_met.v1.E2SmMetIndicationHeader
	(*IndicationHeaderFormats)(nil),              // 20: e2sm_met.v1.IndicationHeaderFormats
	(*E2SmMetIndicationHeaderFormat1)(nil),       // 21: e2sm_met.v1.E2SmMetIndicationHeaderFormat1
	(*E2SmMetIndicationMessage)(nil),             // 22: e2sm_met.v1.E2SmMetIndicationMessage
	(*IndicationMessageFormats)(nil),             // 23: e2sm_met.v1.IndicationMessageFormats
	(*E2SmMetIndicationMessageFormat1)(nil),      // 24: e2sm_met.v1.E2SmMetIndicationMessageFormat1
	(*E2SmMetRanfunctionDescription)(nil),        // 25: e2sm_met.v1.E2SmMetRanfunctionDescription
	(*TimeStamp)(nil),                            // 26: e2sm_met.v1.TimeStamp
	(*Uetag)(nil),                                // 27: e2sm_met.v1.Uetag
}
var file_e2sm_met_v1_e2sm_met_proto_depIdxs = []int32{
	9,  // 0: e2sm_met.v1.Ueitem.ue_id:type_name -> e2sm_met.v1.Ueid
	27, // 1: e2sm_met.v1.Ueitem.ue_tag:type_name -> e2sm_met.v1.Uetag
	12, // 2: e2sm_met.v1.MeasurementInfoList.value:type_name -> e2sm_met.v1.MeasurementInfoItem
	14, // 3: e2sm_met.v1.MeasurementData.value:type_name -> e2sm_met.v1.MeasurementRecord
	9,  // 4: e2sm_met.v1.MeasurementRecord.ue_id:type_name -> e2sm_met.v1.Ueid
	27, // 5: e2sm_met.v1.MeasurementRecord.ue_tag:type_name -> e2sm_met.v1.Uetag
	15, // 6: e2sm_met.v1.MeasurementRecord.meas_record_item:type_name -> e2sm_met.v1.MeasurementRecordItem
	17, // 7: e2sm_met.v1.E2SmMetEventTriggerDefinition.event_definition_formats:type_name -> e2sm_met.v1.EventTriggerDefinitionFormats
	18, // 8: e2sm_met.v1.EventTriggerDefinitionFormats.event_definition_format1:type_name -> e2sm_met.v1.E2SmMetEventTriggerDefinitionFormat1
	20, // 9: e2sm_met.v1.E2SmMetIndicationHeader.indication_header_formats:type_name -> e2sm_met.v1.IndicationHeaderFormats
	21, // 10: e2sm_met.v1.IndicationHeaderFormats.indication_header_format1:type_name -> e2sm_met.v1.E2SmMetIndicationHeaderFormat1
	26, // 11: e2sm_met.v1.E2SmMetIndicationHeaderFormat1.collet_start_time:type_name -> e2sm_met.v1.TimeStamp
	3,  // 12: e2sm_met.v1.E2SmMetIndicationHeaderFormat1.met_node_id:type_name -> e2sm_met.v1.GlobalMetnodeId
	23, // 13: e2sm_met.v1.E2SmMetIndicationMessage.indication_message_formats:type_name -> e2sm_met.v1.IndicationMessageFormats
	24, // 14: e2sm_met.v1.IndicationMessageFormats.indication_message_format1:type_name -> e2sm_met.v1.E2SmMetIndicationMessageFormat1
	2,  // 15: e2sm_met.v1.E2SmMetIndicationMessageFormat1.subscript_id:type_name -> e2sm_met.v1.SubscriptionId
	0,  // 16: e2sm_met.v1.E2SmMetIndicationMessageFormat1.cell_obj_id:type_name -> e2sm_met.v1.CellObjectId
	1,  // 17: e2sm_met.v1.E2SmMetIndicationMessageFormat1.granul_period:type_name -> e2sm_met.v1.GranularityPeriod
	11, // 18: e2sm_met.v1.E2SmMetIndicationMessageFormat1.meas_info_list:type_name -> e2sm_met.v1.MeasurementInfoList
	13, // 19: e2sm_met.v1.E2SmMetIndicationMessageFormat1.meas_data:type_name -> e2sm_met.v1.MeasurementData
	4,  // 20: e2sm_met.v1.E2SmMetRanfunctionDescription.ran_function_name:type_name -> e2sm_met.v1.RanfunctionName
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_e2sm_met_v1_e2sm_met_proto_init() }
func file_e2sm_met_v1_e2sm_met_proto_init() {
	if File_e2sm_met_v1_e2sm_met_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CellObjectId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GranularityPeriod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscriptionId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalMetnodeId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RanfunctionName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaxnoofMeasurementInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaxnoofMeasurementRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaxnoofMeasurementValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaxofUe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ueid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ueitem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeasurementInfoList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeasurementInfoItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeasurementData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeasurementRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeasurementRecordItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*E2SmMetEventTriggerDefinition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventTriggerDefinitionFormats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*E2SmMetEventTriggerDefinitionFormat1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*E2SmMetIndicationHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndicationHeaderFormats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*E2SmMetIndicationHeaderFormat1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*E2SmMetIndicationMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndicationMessageFormats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*E2SmMetIndicationMessageFormat1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*E2SmMetRanfunctionDescription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeStamp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e2sm_met_v1_e2sm_met_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Uetag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_e2sm_met_v1_e2sm_met_proto_msgTypes[10].OneofWrappers = []interface{}{}
	file_e2sm_met_v1_e2sm_met_proto_msgTypes[15].OneofWrappers = []interface{}{
		(*MeasurementRecordItem_Integer)(nil),
		(*MeasurementRecordItem_Real)(nil),
		(*MeasurementRecordItem_NoValue)(nil),
	}
	file_e2sm_met_v1_e2sm_met_proto_msgTypes[17].OneofWrappers = []interface{}{
		(*EventTriggerDefinitionFormats_EventDefinitionFormat1)(nil),
	}
	file_e2sm_met_v1_e2sm_met_proto_msgTypes[20].OneofWrappers = []interface{}{
		(*IndicationHeaderFormats_IndicationHeaderFormat1)(nil),
	}
	file_e2sm_met_v1_e2sm_met_proto_msgTypes[21].OneofWrappers = []interface{}{}
	file_e2sm_met_v1_e2sm_met_proto_msgTypes[23].OneofWrappers = []interface{}{
		(*IndicationMessageFormats_IndicationMessageFormat1)(nil),
	}
	file_e2sm_met_v1_e2sm_met_proto_msgTypes[24].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_e2sm_met_v1_e2sm_met_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_e2sm_met_v1_e2sm_met_proto_goTypes,
		DependencyIndexes: file_e2sm_met_v1_e2sm_met_proto_depIdxs,
		MessageInfos:      file_e2sm_met_v1_e2sm_met_proto_msgTypes,
	}.Build()
	File_e2sm_met_v1_e2sm_met_proto = out.File
	file_e2sm_met_v1_e2sm_met_proto_rawDesc = nil
	file_e2sm_met_v1_e2sm_met_proto_goTypes = nil
	file_e2sm_met_v1_e2sm_met_proto_depIdxs = nil
}
